version: '3'
services:
  python:
    build: ./src
    links:
      - db
    depends_on:
      - db
    environment:
      - POSTGRES_DB=analytics_project
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
    volumes:
      - ./src:/app
      - J:/analytics_project/data:/data
      - J:/analytics_project/plots:/plots
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=analytics_project
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    volumes:
      - analytics_project-postgresql/var/lib/postgresql/data
volumes:
  analytics_project-postgresql:
    external: true
